# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "87d90090dd00b1d5fe09301727899bb9"
name = "Cognito Assistant"
application_url = "https://bot.cognitoinnovations.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[access.admin]
direct_api_mode = "offline"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://bot.cognitoinnovations.com/auth/callback",
  "https://bot.cognitoinnovations.com/auth/shopify/callback",
  "https://bot.cognitoinnovations.com/api/auth/callback"
]
