# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12f3ff297ca026a165ba1a925b73aa90"
name = "prod-chatbot"
handle = "prod-chatbot-1"
application_url = "https://delight-management-titten-try.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://delight-management-titten-try.trycloudflare.com/auth/callback",
  "https://delight-management-titten-try.trycloudflare.com/auth/shopify/callback",
  "https://delight-management-titten-try.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://delight-management-titten-try.trycloudflare.com"
subpath = "chatbot-api"
prefix = "apps"

[pos]
embedded = false
