# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5c6356e63895028f5c0c531b2f8c9846"
name = "Reezo AI"
handle = "reezo-ai-1"
application_url = "https://leading-guestbook-tucson-carb.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,read_products,write_products"

[auth]
redirect_urls = [
  "https://leading-guestbook-tucson-carb.trycloudflare.com/auth/callback",
  "https://leading-guestbook-tucson-carb.trycloudflare.com/auth/shopify/callback",
  "https://leading-guestbook-tucson-carb.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://leading-guestbook-tucson-carb.trycloudflare.com"
subpath = "chatbot-api-1"
prefix = "apps"

[pos]
embedded = false
