# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "805bcae4a3ca70062bf8b2037c5dd508"
name = "test-chatbot"
handle = "test-chatbot-7"
application_url = "https://85fd-2401-4900-ac87-9c52-1c4f-a544-8bf2-9d7a.ngrok-free.app"
embedded = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://85fd-2401-4900-ac87-9c52-1c4f-a544-8bf2-9d7a.ngrok-free.app/auth/callback",
  "https://85fd-2401-4900-ac87-9c52-1c4f-a544-8bf2-9d7a.ngrok-free.app/auth/shopify/callback",
  "https://85fd-2401-4900-ac87-9c52-1c4f-a544-8bf2-9d7a.ngrok-free.app/api/auth/callback"
]

[app_proxy]
url = "https://85fd-2401-4900-ac87-9c52-1c4f-a544-8bf2-9d7a.ngrok-free.app"
subpath = "chatbot-api"
prefix = "apps"

[pos]
embedded = false

[web]
port = 3_000

[build]
automatically_update_urls_on_dev = true
