# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0b0088138bf915307e7b51a6a9973f68"
name = "chatbot"
handle = "chatbot-234"
application_url = "https://sending-peak-jumping-finally.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,read_products,write_products"

[auth]
redirect_urls = [
  "https://sending-peak-jumping-finally.trycloudflare.com/auth/callback",
  "https://sending-peak-jumping-finally.trycloudflare.com/auth/shopify/callback",
  "https://sending-peak-jumping-finally.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://sending-peak-jumping-finally.trycloudflare.com"
subpath = "chatbot-api"
prefix = "apps"

[pos]
embedded = false
