# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "67b60e150ad6ac22d3e9033198b5a89f"
application_url = "https://wrote-counting-christine-acids.trycloudflare.com"
embedded = true
name = "test-app"
handle = "test-app-11683"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://wrote-counting-christine-acids.trycloudflare.com/auth/callback",
  "https://wrote-counting-christine-acids.trycloudflare.com/auth/shopify/callback",
  "https://wrote-counting-christine-acids.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://wrote-counting-christine-acids.trycloudflare.com"
subpath = "chatbot-api"
prefix = "apps"

[pos]
embedded = false
