# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a5e63b353544300e41f67086b871d4ae"
application_url = "https://silent-spatial-rg-presentation.trycloudflare.com"
embedded = true
name = "chatbot-test"
handle = "chatbot-test-15"

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://silent-spatial-rg-presentation.trycloudflare.com/auth/callback",
  "https://silent-spatial-rg-presentation.trycloudflare.com/auth/shopify/callback",
  "https://silent-spatial-rg-presentation.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://silent-spatial-rg-presentation.trycloudflare.com"
subpath = "chatbot-api"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
