# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "82de5a9b4e203504a893c74b77a2460a"
name = "test-chatbot"
handle = "test-chatbot-5"
application_url = "https://87cf-2401-4900-5608-ee3-5da9-430e-2ac9-47d0.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://87cf-2401-4900-5608-ee3-5da9-430e-2ac9-47d0.ngrok-free.app/auth/callback",
  "https://87cf-2401-4900-5608-ee3-5da9-430e-2ac9-47d0.ngrok-free.app/auth/shopify/callback",
  "https://87cf-2401-4900-5608-ee3-5da9-430e-2ac9-47d0.ngrok-free.app/api/auth/callback"
]

[app_proxy]
url = "https://87cf-2401-4900-5608-ee3-5da9-430e-2ac9-47d0.ngrok-free.app"
subpath = "chatbot-api"
prefix = "apps"

[pos]
embedded = false

[web]
port = 3_000
