# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2e63e2ef0febbcddb9c7bc386f2f228"
application_url = "https://tt-est-confirmed-monsters.trycloudflare.com"
embedded = true
name = "chatbot"
handle = "chatbot-216"

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://tt-est-confirmed-monsters.trycloudflare.com/auth/callback",
  "https://tt-est-confirmed-monsters.trycloudflare.com/auth/shopify/callback",
  "https://tt-est-confirmed-monsters.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://tt-est-confirmed-monsters.trycloudflare.com"
subpath = "chatbot-api"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
