# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "87869605ef99cb19747c1116d0a124d8"
name = "prod-chatbot"
handle = "prod-chatbot"
application_url = "https://popularity-diy-performed-constitutes.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://popularity-diy-performed-constitutes.trycloudflare.com/auth/callback",
  "https://popularity-diy-performed-constitutes.trycloudflare.com/auth/shopify/callback",
  "https://popularity-diy-performed-constitutes.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
