# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "219c1c8dbe42911175fe6cfb1572779f"
name = "chatbot-v8"
application_url = "https://photographer-casting-homeland-equipped.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
    "https://photographer-casting-homeland-equipped.trycloudflare.com/auth/callback",
    "https://photographer-casting-homeland-equipped.trycloudflare.com/auth/shopify/callback",
    "https://photographer-casting-homeland-equipped.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://photographer-casting-homeland-equipped.trycloudflare.com"
subpath = "chatbot-api-1"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
