"""add shop_id to collections and create composite unique constraint

Revision ID: 08031a9cd4cc
Revises: ddfdfc48b706
Create Date: 2025-10-14 12:19:32.548127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08031a9cd4cc'
down_revision: Union[str, None] = 'ddfdfc48b706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('collections_title_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_collections_title'), ['title'], unique=False)
        batch_op.create_unique_constraint('_shop_id_title_uc', ['shop_id', 'title'])
        batch_op.create_foreign_key(
            'fk_collections_shop_id_shops', 
            'shops', 
            ['shop_id'], 
            ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_collections_shop_id_shops', type_='foreignkey')
        batch_op.drop_constraint('_shop_id_title_uc', type_='unique')
        batch_op.drop_index(batch_op.f('ix_collections_title'))
        batch_op.create_unique_constraint('collections_title_key', ['title'])
        batch_op.drop_column('shop_id')

    # ### end Alembic commands ###
