"""add user_shop_minutely_analytics table

Revision ID: 1caa5b3e2c22
Revises: ee2cfbc2a750
Create Date: 2025-10-09 12:38:47.243298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1caa5b3e2c22'
down_revision: Union[str, None] = 'ee2cfbc2a750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_shop_minutely_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.String(length=255), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('minute_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False),
    sa.Column('chat_interactions_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('opened_chatbot_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('added_to_cart_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('purchased_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('purchase_amount', sa.Float(), server_default='0.0', nullable=False),
    sa.CheckConstraint('(user_id IS NOT NULL AND guest_id IS NULL) OR (user_id IS NULL AND guest_id IS NOT NULL)', name='check_minutely_user_or_guest'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create standard indexes
    op.create_index(op.f('ix_user_shop_minutely_analytics_user_id'), 'user_shop_minutely_analytics', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_shop_minutely_analytics_guest_id'), 'user_shop_minutely_analytics', ['guest_id'], unique=False)
    op.create_index(op.f('ix_user_shop_minutely_analytics_shop_id'), 'user_shop_minutely_analytics', ['shop_id'], unique=False)
    op.create_index(op.f('ix_user_shop_minutely_analytics_minute_timestamp'), 'user_shop_minutely_analytics', ['minute_timestamp'], unique=False)
    op.create_index(op.f('ix_user_shop_minutely_analytics_date'), 'user_shop_minutely_analytics', ['date'], unique=False)

    # Create partial unique indexes
    op.create_index(
        'uq_minutely_user_shop_minute', 
        'user_shop_minutely_analytics', 
        ['user_id', 'shop_id', 'minute_timestamp'], 
        unique=True, 
        postgresql_where=sa.text('user_id IS NOT NULL')
    )
    op.create_index(
        'uq_minutely_guest_shop_minute', 
        'user_shop_minutely_analytics', 
        ['guest_id', 'shop_id', 'minute_timestamp'], 
        unique=True, 
        postgresql_where=sa.text('guest_id IS NOT NULL')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_shop_minutely_analytics')
    # ### end Alembic commands ###
