"""Add product foreign key to offers table

Revision ID: 2750275dac46
Revises: 59bfe9b460be
Create Date: 2025-10-01 18:01:21.934507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2750275dac46'
down_revision: Union[str, None] = '59bfe9b460be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('product_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('_tag_shop_uc', 'offers', type_='unique')
    op.create_unique_constraint('_tag_product_uc', 'offers', ['tag', 'product_id'])
    op.create_foreign_key(None, 'offers', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_offers_product_id_products'), 'offers', type_='foreignkey')
    op.drop_constraint('_tag_product_uc', 'offers', type_='unique')
    op.create_unique_constraint('_tag_shop_uc', 'offers', ['tag', 'shop_id'])
    op.drop_column('offers', 'product_id')
    # ### end Alembic commands ###