"""App schema alignment (integrations FK, products, analytics, users).

Revision ID: 405d516f0c7f
Revises: 5c546a3fe049
Create Date: 2026-05-01 14:10:16.112511

Replaces an autogenerated revision that attempted to DROP Supabase-managed
schemas (auth, storage, realtime, vault). Those operations require object
ownership the app role does not have and must never run from app migrations.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "405d516f0c7f"
down_revision: Union[str, None] = "5c546a3fe049"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "integrations",
        "shop_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint("integrations_shop_id_fkey", "integrations", type_="foreignkey")
    op.create_foreign_key(
        "integrations_shop_id_fkey",
        "integrations",
        "shops",
        ["shop_id"],
        ["id"],
    )
    op.add_column(
        "products",
        sa.Column("variant_quantity", sa.Integer(), nullable=True),
    )
    op.alter_column(
        "shop_metadata",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "shop_metadata",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_shop_minutely_analytics",
        "chat_interactions_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user_shop_minutely_analytics",
        "opened_chatbot_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user_shop_minutely_analytics",
        "added_to_cart_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user_shop_minutely_analytics",
        "purchased_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user_shop_minutely_analytics",
        "purchase_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )


def downgrade() -> None:
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_shop_minutely_analytics",
        "purchase_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'0'::double precision"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_shop_minutely_analytics",
        "purchased_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_shop_minutely_analytics",
        "added_to_cart_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_shop_minutely_analytics",
        "opened_chatbot_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_shop_minutely_analytics",
        "chat_interactions_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "shop_metadata",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "shop_metadata",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("products", "variant_quantity")
    op.drop_constraint("integrations_shop_id_fkey", "integrations", type_="foreignkey")
    op.create_foreign_key(
        "integrations_shop_id_fkey",
        "integrations",
        "shops",
        ["shop_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "integrations",
        "shop_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
