"""change IntegrationModel.shop_id to reference shops.id instead of shops.shop_id

Revision ID: 505a869a82d9
Revises: 08031a9cd4cc
Create Date: 2025-10-15 11:02:24.627545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '505a869a82d9'
down_revision: Union[str, None] = '08031a9cd4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('shop_id_new', sa.Integer(), nullable=True))

    op.execute("""
        UPDATE integrations AS i
        SET shop_id_new = s.id
        FROM shops AS s
        WHERE i.shop_id = s.shop_id
    """)

    op.drop_constraint('integrations_shop_id_fkey', 'integrations', type_='foreignkey')
    op.drop_column('integrations', 'shop_id')

    op.alter_column('integrations', 'shop_id_new', new_column_name='shop_id', existing_type=sa.Integer())

    op.create_foreign_key(
        'integrations_shop_id_fkey',
        'integrations',
        'shops',
        ['shop_id'],
        ['id'],
        ondelete='CASCADE'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('shop_id_old', sa.String(), nullable=True))

    op.execute("""
        UPDATE integrations AS i
        SET shop_id_old = s.shop_id
        FROM shops AS s
        WHERE i.shop_id = s.id
    """)

    op.drop_constraint('integrations_shop_id_fkey', 'integrations', type_='foreignkey')
    op.drop_column('integrations', 'shop_id')

    op.alter_column('integrations', 'shop_id_old', new_column_name='shop_id', existing_type=sa.String())

    op.create_foreign_key(
        'integrations_shop_id_fkey',
        'integrations',
        'shops',
        ['shop_id'],
        ['shop_id'],
        ondelete='CASCADE'
    )

    # ### end Alembic commands ###
