"""Remove Cart table and merge keys into CartItem

Revision ID: 5c546a3fe049
Revises: c7bcc136cacf
Create Date: 2025-11-05 15:07:15.361757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5c546a3fe049'
down_revision: Union[str, None] = 'c7bcc136cacf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('cart_items', sa.Column('shop_id', sa.Integer(), nullable=True))

    op.execute("""
        UPDATE cart_items AS ci
        SET 
            user_id = c.user_id,
            shop_id = c.shop_id
        FROM carts AS c
        WHERE ci.cart_id = c.id
    """)

    op.alter_column('cart_items', 'user_id', nullable=False)
    op.alter_column('cart_items', 'shop_id', nullable=False)

    op.create_index(op.f('ix_cart_items_shop_id'), 'cart_items', ['shop_id'], unique=False)
    op.create_index(op.f('ix_cart_items_user_id'), 'cart_items', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_cart_items_user_id_users'), 'cart_items', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_cart_items_shop_id_shops'), 'cart_items', 'shops', ['shop_id'], ['id'])

    op.drop_constraint('uq_cart_variant', 'cart_items', type_='unique')
    
    op.create_unique_constraint(op.f('uq_user_shop_variant'), 'cart_items', ['user_id', 'shop_id', 'variant_id'])

    op.drop_index('ix_cart_items_cart_id', table_name='cart_items')
    op.drop_constraint(op.f('cart_items_cart_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'cart_id')

    op.drop_table('carts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=False),
        sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name='fk_carts_shop_id_shops'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_carts_user_id_users'),
        sa.PrimaryKeyConstraint('id', name='pk_carts'),
        sa.UniqueConstraint('user_id', 'shop_id', name='uq_user_shop_cart')
    )
    op.create_index('ix_carts_user_id', 'carts', ['user_id'], unique=False)
    op.create_index('ix_carts_shop_id', 'carts', ['shop_id'], unique=False)

    op.add_column('cart_items', sa.Column('cart_id', sa.INTEGER(), nullable=True))

    op.execute("""
        INSERT INTO carts (user_id, shop_id, created_at, updated_at)
        SELECT DISTINCT user_id, shop_id, MIN(created_at), MAX(updated_at)
        FROM cart_items
        GROUP BY user_id, shop_id
    """)
    
    op.execute("""
        UPDATE cart_items AS ci
        SET cart_id = c.id
        FROM carts AS c
        WHERE ci.user_id = c.user_id AND ci.shop_id = c.shop_id
    """)

    op.alter_column('cart_items', 'cart_id', nullable=False)

    op.create_index('ix_cart_items_cart_id', 'cart_items', ['cart_id'], unique=False)
    op.create_foreign_key(op.f('fk_cart_items_cart_id_carts'), 'cart_items', 'carts', ['cart_id'], ['id'])

    op.drop_constraint(op.f('uq_user_shop_variant'), 'cart_items', type_='unique')
    
    op.create_unique_constraint('uq_cart_variant', 'cart_items', ['cart_id', 'variant_id'])

    op.drop_constraint(op.f('fk_cart_items_shop_id_shops'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_cart_items_user_id_users'), 'cart_items', type_='foreignkey')
    op.drop_index(op.f('ix_cart_items_user_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_shop_id'), table_name='cart_items')
    op.drop_column('cart_items', 'shop_id')
    op.drop_column('cart_items', 'user_id')
    # ### end Alembic commands ###

