"""remove OTP model

Revision ID: 655bc24dcb8d
Revises: 39e9315072bf
Create Date: 2025-07-22 12:25:25.479449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '655bc24dcb8d'
down_revision: Union[str, None] = '39e9315072bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otps_email'), table_name='otps')
    op.drop_table('otps')
    # ### end Alembic commands ###
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_challenges',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('factor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=False),
    sa.Column('otp_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('web_authn_session_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['factor_id'], ['auth.mfa_factors.id'], name=op.f('mfa_challenges_auth_factor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mfa_challenges_pkey')),
    schema='auth',
    comment='auth: stores metadata about challenge requests made'
    )
    op.create_index(op.f('mfa_challenge_created_at_idx'), 'mfa_challenges', [sa.literal_column('created_at DESC')], unique=False, schema='auth')
    op.create_table('otps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('otps_pkey'))
    )
    op.create_index(op.f('ix_otps_email'), 'otps', ['email'], unique=False)
    op.create_table('objects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('bucket_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.UUID(), autoincrement=False, nullable=True, comment='Field is deprecated, use owner_id instead'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_accessed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('path_tokens', postgresql.ARRAY(sa.TEXT()), sa.Computed("string_to_array(name, '/'::text)", persisted=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['storage.buckets.id'], name=op.f('objects_bucketId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('objects_pkey')),
    schema='storage'
    )
    op.create_index(op.f('name_prefix_search'), 'objects', ['name'], unique=False, schema='storage')
    op.create_index(op.f('idx_objects_bucket_id_name'), 'objects', ['bucket_id', 'name'], unique=False, schema='storage')
    op.create_index(op.f('bucketid_objname'), 'objects', ['bucket_id', 'name'], unique=True, schema='storage')
    op.create_table('identities',
    sa.Column('provider_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('identity_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_sign_in_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), sa.Computed("lower((identity_data ->> 'email'::text))", persisted=True), autoincrement=False, nullable=True, comment='Auth: Email is a generated column that references the optional email property in the identity_data'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('identities_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('identities_pkey')),
    sa.UniqueConstraint('provider_id', 'provider', name=op.f('identities_provider_id_provider_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth',
    comment='Auth: Stores identities associated to a user.'
    )
    op.create_index(op.f('identities_user_id_idx'), 'identities', ['user_id'], unique=False, schema='auth')
    op.create_index(op.f('identities_email_idx'), 'identities', ['email'], unique=False, schema='auth')
    op.create_table('messages',
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('private', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'inserted_at', name=op.f('messages_pkey')),
    schema='realtime'
    )
    op.create_table('sso_providers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.TEXT(), autoincrement=False, nullable=True, comment='Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint('resource_id = NULL::text OR char_length(resource_id) > 0', name='resource_id not empty'),
    sa.PrimaryKeyConstraint('id', name='sso_providers_pkey'),
    schema='auth',
    comment='Auth: Manages SSO identity provider information; see saml_providers for SAML.',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('sso_providers_resource_id_idx'), 'sso_providers', [sa.literal_column('lower(resource_id)')], unique=True, schema='auth')
    op.create_table('saml_providers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sso_provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata_xml', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attribute_mapping', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('name_id_format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('char_length(entity_id) > 0', name=op.f('entity_id not empty')),
    sa.CheckConstraint('char_length(metadata_xml) > 0', name=op.f('metadata_xml not empty')),
    sa.CheckConstraint('metadata_url = NULL::text OR char_length(metadata_url) > 0', name=op.f('metadata_url not empty')),
    sa.ForeignKeyConstraint(['sso_provider_id'], ['auth.sso_providers.id'], name=op.f('saml_providers_sso_provider_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('saml_providers_pkey')),
    sa.UniqueConstraint('entity_id', name=op.f('saml_providers_entity_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth',
    comment='Auth: Manages SAML Identity Provider connections.'
    )
    op.create_index(op.f('saml_providers_sso_provider_id_idx'), 'saml_providers', ['sso_provider_id'], unique=False, schema='auth')
    op.create_table('one_time_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_type', postgresql.ENUM('confirmation_token', 'reauthentication_token', 'recovery_token', 'email_change_token_new', 'email_change_token_current', 'phone_change_token', name='one_time_token_type', schema='auth'), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('relates_to', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('char_length(token_hash) > 0', name=op.f('one_time_tokens_token_hash_check')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('one_time_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('one_time_tokens_pkey')),
    schema='auth'
    )
    op.create_index(op.f('one_time_tokens_user_id_token_type_key'), 'one_time_tokens', ['user_id', 'token_type'], unique=True, schema='auth')
    op.create_index(op.f('one_time_tokens_token_hash_hash_idx'), 'one_time_tokens', ['token_hash'], unique=False, schema='auth', postgresql_using='hash')
    op.create_index(op.f('one_time_tokens_relates_to_hash_idx'), 'one_time_tokens', ['relates_to'], unique=False, schema='auth', postgresql_using='hash')
    op.create_table('s3_multipart_uploads',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('in_progress_size', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('upload_signature', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bucket_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['storage.buckets.id'], name='s3_multipart_uploads_bucket_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='s3_multipart_uploads_pkey'),
    schema='storage',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_multipart_uploads_list'), 's3_multipart_uploads', ['bucket_id', 'key', 'created_at'], unique=False, schema='storage')
    op.create_table('s3_multipart_uploads_parts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('upload_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('size', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('part_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bucket_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('etag', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['storage.buckets.id'], name=op.f('s3_multipart_uploads_parts_bucket_id_fkey')),
    sa.ForeignKeyConstraint(['upload_id'], ['storage.s3_multipart_uploads.id'], name=op.f('s3_multipart_uploads_parts_upload_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('s3_multipart_uploads_parts_pkey')),
    schema='storage'
    )
    op.create_table('secrets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('secret', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nonce', postgresql.BYTEA(), server_default=sa.text('vault._crypto_aead_det_noncegen()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('secrets_pkey')),
    schema='vault',
    comment='Table with encrypted `secret` column for storing sensitive information on disk.'
    )
    op.create_index(op.f('secrets_name_idx'), 'secrets', ['name'], unique=True, schema='vault', postgresql_where='(name IS NOT NULL)')
    op.create_table('flow_state',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('auth_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code_challenge_method', postgresql.ENUM('s256', 'plain', name='code_challenge_method', schema='auth'), autoincrement=False, nullable=False),
    sa.Column('code_challenge', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider_access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider_refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('authentication_method', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('auth_code_issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='flow_state_pkey'),
    schema='auth',
    comment='stores metadata for pkce logins',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_user_id_auth_method'), 'flow_state', ['user_id', 'authentication_method'], unique=False, schema='auth')
    op.create_index(op.f('idx_auth_code'), 'flow_state', ['auth_code'], unique=False, schema='auth')
    op.create_index(op.f('flow_state_created_at_idx'), 'flow_state', [sa.literal_column('created_at DESC')], unique=False, schema='auth')
    op.create_table('sso_domains',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sso_provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint('char_length(domain) > 0', name=op.f('domain not empty')),
    sa.ForeignKeyConstraint(['sso_provider_id'], ['auth.sso_providers.id'], name=op.f('sso_domains_sso_provider_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sso_domains_pkey')),
    schema='auth',
    comment='Auth: Manages SSO email address domain mapping to an SSO Identity Provider.'
    )
    op.create_index(op.f('sso_domains_sso_provider_id_idx'), 'sso_domains', ['sso_provider_id'], unique=False, schema='auth')
    op.create_index(op.f('sso_domains_domain_idx'), 'sso_domains', [sa.literal_column('lower(domain)')], unique=True, schema='auth')
    op.create_table('saml_relay_states',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sso_provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('for_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('redirect_to', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('flow_state_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint('char_length(request_id) > 0', name=op.f('request_id not empty')),
    sa.ForeignKeyConstraint(['flow_state_id'], ['auth.flow_state.id'], name=op.f('saml_relay_states_flow_state_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sso_provider_id'], ['auth.sso_providers.id'], name=op.f('saml_relay_states_sso_provider_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('saml_relay_states_pkey')),
    schema='auth',
    comment='Auth: Contains SAML Relay State information for each Service Provider initiated login.'
    )
    op.create_index(op.f('saml_relay_states_sso_provider_id_idx'), 'saml_relay_states', ['sso_provider_id'], unique=False, schema='auth')
    op.create_index(op.f('saml_relay_states_for_email_idx'), 'saml_relay_states', ['for_email'], unique=False, schema='auth')
    op.create_index(op.f('saml_relay_states_created_at_idx'), 'saml_relay_states', [sa.literal_column('created_at DESC')], unique=False, schema='auth')
    op.create_table('mfa_amr_claims',
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('authentication_method', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['auth.sessions.id'], name=op.f('mfa_amr_claims_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('amr_id_pk')),
    sa.UniqueConstraint('session_id', 'authentication_method', name=op.f('mfa_amr_claims_session_id_authentication_method_pkey'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth',
    comment='auth: stores authenticator method reference claims for multi factor authentication'
    )
    op.create_table('buckets',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner', sa.UUID(), autoincrement=False, nullable=True, comment='Field is deprecated, use owner_id instead'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('avif_autodetection', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('file_size_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('allowed_mime_types', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('buckets_pkey')),
    schema='storage'
    )
    op.create_index(op.f('bname'), 'buckets', ['name'], unique=True, schema='storage')
    op.create_table('schema_migrations',
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('version', name=op.f('schema_migrations_pkey')),
    schema='realtime'
    )
    op.create_table('audit_log_entries',
    sa.Column('instance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_entries_pkey')),
    schema='auth',
    comment='Auth: Audit trail for user actions.'
    )
    op.create_index(op.f('audit_logs_instance_id_idx'), 'audit_log_entries', ['instance_id'], unique=False, schema='auth')
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'CANCELED', 'PAST_DUE', 'INCOMPLETE', 'INCOMPLETE_EXPIRED', 'TRIALING', 'UNPAID', name='subscriptionstatus'), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('subscriptions_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey'))
    )
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_shop_id'), 'subscriptions', ['shop_id'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity', postgresql.REGCLASS(), autoincrement=False, nullable=False),
    sa.Column('filters', sa.NullType(), server_default=sa.text("'{}'::realtime.user_defined_filter[]"), autoincrement=False, nullable=False),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('claims_role', sa.NullType(), sa.Computed("realtime.to_regrole((claims ->> 'role'::text))", persisted=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription')),
    schema='realtime'
    )
    op.create_index(op.f('subscription_subscription_id_entity_filters_key'), 'subscription', ['subscription_id', 'entity', 'filters'], unique=True, schema='realtime')
    op.create_index(op.f('ix_realtime_subscription_entity'), 'subscription', ['entity'], unique=False, schema='realtime')
    op.create_table('users',
    sa.Column('instance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('aud', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('encrypted_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('invited_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('confirmation_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('confirmation_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('recovery_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recovery_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('email_change_token_new', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_change', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_change_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_sign_in_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('raw_app_meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_user_meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_super_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('phone_confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('phone_change', sa.TEXT(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('phone_change_token', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('phone_change_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), sa.Computed('LEAST(email_confirmed_at, phone_confirmed_at)', persisted=True), autoincrement=False, nullable=True),
    sa.Column('email_change_token_current', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('email_change_confirm_status', sa.SMALLINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('banned_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reauthentication_token', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('reauthentication_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_sso_user', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_anonymous', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.CheckConstraint('email_change_confirm_status >= 0 AND email_change_confirm_status <= 2', name='users_email_change_confirm_status_check'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('phone', name='users_phone_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth',
    comment='Auth: Stores user login data within a secure schema.',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('users_is_anonymous_idx'), 'users', ['is_anonymous'], unique=False, schema='auth')
    op.create_index(op.f('users_instance_id_idx'), 'users', ['instance_id'], unique=False, schema='auth')
    op.create_index(op.f('users_instance_id_email_idx'), 'users', ['instance_id', sa.literal_column('lower(email::text)')], unique=False, schema='auth')
    op.create_index(op.f('users_email_partial_key'), 'users', ['email'], unique=True, schema='auth', postgresql_where='(is_sso_user = false)')
    op.create_index(op.f('recovery_token_idx'), 'users', ['recovery_token'], unique=True, schema='auth', postgresql_where="((recovery_token)::text !~ '^[0-9 ]*$'::text)")
    op.create_index(op.f('reauthentication_token_idx'), 'users', ['reauthentication_token'], unique=True, schema='auth', postgresql_where="((reauthentication_token)::text !~ '^[0-9 ]*$'::text)")
    op.create_index(op.f('email_change_token_new_idx'), 'users', ['email_change_token_new'], unique=True, schema='auth', postgresql_where="((email_change_token_new)::text !~ '^[0-9 ]*$'::text)")
    op.create_index(op.f('email_change_token_current_idx'), 'users', ['email_change_token_current'], unique=True, schema='auth', postgresql_where="((email_change_token_current)::text !~ '^[0-9 ]*$'::text)")
    op.create_index(op.f('confirmation_token_idx'), 'users', ['confirmation_token'], unique=True, schema='auth', postgresql_where="((confirmation_token)::text !~ '^[0-9 ]*$'::text)")
    op.create_table('schema_migrations',
    sa.Column('version', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('schema_migrations_pkey')),
    schema='auth',
    comment='Auth: Manages updates to the auth system.'
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('executed_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('migrations_pkey')),
    sa.UniqueConstraint('name', name=op.f('migrations_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='storage'
    )
    op.create_table('refresh_tokens',
    sa.Column('instance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('parent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['auth.sessions.id'], name=op.f('refresh_tokens_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('refresh_tokens_token_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth',
    comment='Auth: Store of tokens used to refresh JWT tokens once they expire.'
    )
    op.create_index(op.f('refresh_tokens_updated_at_idx'), 'refresh_tokens', [sa.literal_column('updated_at DESC')], unique=False, schema='auth')
    op.create_index(op.f('refresh_tokens_session_id_revoked_idx'), 'refresh_tokens', ['session_id', 'revoked'], unique=False, schema='auth')
    op.create_index(op.f('refresh_tokens_parent_idx'), 'refresh_tokens', ['parent'], unique=False, schema='auth')
    op.create_index(op.f('refresh_tokens_instance_id_user_id_idx'), 'refresh_tokens', ['instance_id', 'user_id'], unique=False, schema='auth')
    op.create_index(op.f('refresh_tokens_instance_id_idx'), 'refresh_tokens', ['instance_id'], unique=False, schema='auth')
    op.create_table('instances',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('raw_base_config', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('instances_pkey')),
    schema='auth',
    comment='Auth: Manages users across multiple sites.'
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('factor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('aal', postgresql.ENUM('aal1', 'aal2', 'aal3', name='aal_level', schema='auth'), autoincrement=False, nullable=True),
    sa.Column('not_after', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.'),
    sa.Column('refreshed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('tag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey')),
    schema='auth',
    comment='Auth: Stores session data associated to a user.'
    )
    op.create_index(op.f('user_id_created_at_idx'), 'sessions', ['user_id', 'created_at'], unique=False, schema='auth')
    op.create_index(op.f('sessions_user_id_idx'), 'sessions', ['user_id'], unique=False, schema='auth')
    op.create_index(op.f('sessions_not_after_idx'), 'sessions', [sa.literal_column('not_after DESC')], unique=False, schema='auth')
    op.create_table('mfa_factors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('friendly_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('factor_type', postgresql.ENUM('totp', 'webauthn', 'phone', name='factor_type', schema='auth'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('unverified', 'verified', name='factor_status', schema='auth'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('secret', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_challenged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('web_authn_credential', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('web_authn_aaguid', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('mfa_factors_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mfa_factors_pkey')),
    sa.UniqueConstraint('last_challenged_at', name=op.f('mfa_factors_last_challenged_at_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth',
    comment='auth: stores metadata about factors'
    )
    op.create_index(op.f('unique_phone_factor_per_user'), 'mfa_factors', ['user_id', 'phone'], unique=True, schema='auth')
    op.create_index(op.f('mfa_factors_user_id_idx'), 'mfa_factors', ['user_id'], unique=False, schema='auth')
    op.create_index(op.f('mfa_factors_user_friendly_name_unique'), 'mfa_factors', ['friendly_name', 'user_id'], unique=True, schema='auth', postgresql_where="(TRIM(BOTH FROM friendly_name) <> ''::text)")
    op.create_index(op.f('factor_id_created_at_idx'), 'mfa_factors', ['user_id', 'created_at'], unique=False, schema='auth')
    # ### end Alembic commands ###
