"""Remove utm columns from user_shop_analytics

Revision ID: c9d1cf65a0f1
Revises: 505a869a82d9
Create Date: 2025-10-15 18:08:40.064031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d1cf65a0f1'
down_revision: Union[str, None] = '505a869a82d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_shop_analytics', 'utm_source')
    op.drop_column('user_shop_analytics', 'utm_medium')
    op.drop_column('user_shop_analytics', 'utm_campaign')
    op.drop_column('user_shop_analytics', 'utm_term')
    op.drop_column('user_shop_analytics', 'utm_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column('user_shop_analytics', sa.Column('utm_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_shop_analytics', sa.Column('utm_medium', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_shop_analytics', sa.Column('utm_campaign', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_shop_analytics', sa.Column('utm_term', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_shop_analytics', sa.Column('utm_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
