"""testing alembic

Revision ID: cbb8ca4880e5
Revises: 3e3a1ecd5a85
Create Date: 2025-06-15 18:13:02.189141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbb8ca4880e5'
down_revision: Union[str, None] = '3e3a1ecd5a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('otps', 'expired_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('otps', 'expires_at')
    