"""Add unique constraints for user and guest

Revision ID: d7a60fcc258d
Revises: 8312675e7542
Create Date: 2025-09-19 18:28:50.266658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd7a60fcc258d'
down_revision: Union[str, None] = '8312675e7542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_guest_product_in_cart', 'checkout_products', ['shop_id', 'variant_id', 'guest_id'])
    op.create_unique_constraint('uq_user_product_in_cart', 'checkout_products', ['shop_id', 'variant_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_product_in_cart', 'checkout_products', type_='unique')
    op.drop_constraint('uq_guest_product_in_cart', 'checkout_products', type_='unique')
    # ### end Alembic commands ###
